### ISSUE TITLE
the divesity of candidate regions

### ISSUE THREAD

**Issue by yjj-liwei** [gaobb/MCAR#7] opened 2022-05-13 08:46 UTC
How the candidate region diversity is implemented in the code？
Thanks you！

**Comment by gaobb** [comment] 2022-06-10 04:31
please see https://github.com/gaobb/MCAR/issues/6

**Comment by gaobb** [comment] 2022-06-10 04:32
please see https://github.com/gaobb/MCAR/issues/6

**Comment by gaobb** [comment] 2022-06-10 04:33
Duplicate of #https://github.com/gaobb/MCAR/issues/6

**Closed as completed** 2022-06-10 04:35 UTC
Labels: duplicate
